# Generated by Django 5.1.15 on 2026-06-04 23:24

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Score',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nick', models.CharField(max_length=22)),
                ('genre', models.CharField(max_length=64)),
                ('level', models.CharField(choices=[('popcorn', 'Akolita Popcornu'), ('kinoman', 'Samozwańczy Kinoman'), ('kineza', 'Orędownik Wielkiej Kinezy')], max_length=16)),
                ('score', models.IntegerField()),
                ('ts', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='scores', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-score', '-ts'],
                'indexes': [models.Index(fields=['-score'], name='game_score_score_eae92f_idx')],
            },
        ),
    ]
