# Generated by Django 5.2.15 on 2026-06-10 05:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='BlockedFilm',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('film_id', models.IntegerField(unique=True)),
                ('title', models.CharField(blank=True, max_length=120)),
                ('note', models.CharField(blank=True, max_length=200)),
                ('created', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Zablokowany film',
                'verbose_name_plural': 'Zablokowane filmy',
            },
        ),
        migrations.CreateModel(
            name='FrameReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('film_id', models.IntegerField(unique=True)),
                ('title', models.CharField(blank=True, max_length=120)),
                ('reports', models.PositiveIntegerField(default=1)),
                ('last_url', models.URLField(blank=True, max_length=300)),
                ('updated', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Zgłoszenie kadru',
                'verbose_name_plural': 'Zgłoszenia kadrów',
                'ordering': ['-reports', '-updated'],
            },
        ),
        migrations.CreateModel(
            name='BlockedBackdrop',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('film_id', models.IntegerField()),
                ('file_path', models.CharField(max_length=120)),
                ('created', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Zablokowany kadr',
                'verbose_name_plural': 'Zablokowane kadry',
                'unique_together': {('film_id', 'file_path')},
            },
        ),
    ]
