# Generated by Django 5.2.15 on 2026-06-12 18:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0003_set_site_domain'),
    ]

    operations = [
        migrations.CreateModel(
            name='Film',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tmdb_id', models.IntegerField(db_index=True, unique=True)),
                ('title', models.CharField(max_length=200)),
                ('original_title', models.CharField(blank=True, max_length=200)),
                ('director', models.CharField(max_length=120)),
                ('year', models.PositiveSmallIntegerField()),
                ('country', models.CharField(blank=True, help_text='Primary production country', max_length=100)),
                ('countries', models.JSONField(blank=True, default=list, help_text='All production countries')),
                ('genres', models.JSONField(default=list)),
                ('tmdb_rating', models.DecimalField(blank=True, decimal_places=1, max_digits=3, null=True)),
                ('tmdb_vote_count', models.PositiveIntegerField(default=0)),
                ('overview', models.TextField(blank=True)),
                ('poster_path', models.CharField(blank=True, max_length=120)),
                ('runtime', models.IntegerField(blank=True, help_text='Runtime in minutes', null=True)),
                ('tagline', models.CharField(blank=True, max_length=300)),
                ('imdb_id', models.CharField(blank=True, help_text='e.g. tt0111161', max_length=20)),
                ('original_language', models.CharField(blank=True, max_length=10)),
                ('production_companies', models.JSONField(blank=True, default=list)),
                ('belongs_to_collection', models.CharField(blank=True, max_length=200)),
                ('spoken_languages', models.JSONField(blank=True, default=list)),
                ('cast_top5', models.JSONField(blank=True, default=list, help_text='Top 5 actors')),
                ('cinematographer', models.CharField(blank=True, help_text='Director of Photography', max_length=120)),
                ('composer', models.CharField(blank=True, help_text='Original Music Composer', max_length=120)),
                ('keywords', models.JSONField(blank=True, default=list)),
                ('budget', models.BigIntegerField(blank=True, null=True)),
                ('revenue', models.BigIntegerField(blank=True, null=True)),
                ('tier', models.CharField(choices=[('A', 'A — Niche Arthouse'), ('B', 'B — Ambitious / Festival'), ('C', 'C — Popular Quality'), ('D', 'D — Mainstream Classics')], db_index=True, default='C', max_length=1)),
                ('cinema_era', models.CharField(blank=True, choices=[('silent', 'Silent Era (< 1929)'), ('golden', 'Golden Age (1930–1959)'), ('new_wave', 'New Wave (1960–1979)'), ('modern', 'Modern (1980–1999)'), ('contemporary', 'Contemporary (2000+)')], help_text='Auto-calculated from year, manually overridable', max_length=12)),
                ('is_active', models.BooleanField(db_index=True, default=True)),
                ('tmdb_last_synced', models.DateTimeField(blank=True, null=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Film',
                'verbose_name_plural': 'Filmy',
                'ordering': ['title'],
                'indexes': [models.Index(fields=['tier', 'is_active'], name='game_film_tier_f11f7a_idx'), models.Index(fields=['year'], name='game_film_year_dc829a_idx'), models.Index(fields=['cinema_era'], name='game_film_cinema__9423cc_idx')],
            },
        ),
        migrations.CreateModel(
            name='Backdrop',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file_path', models.CharField(max_length=120)),
                ('status', models.CharField(choices=[('active', 'Active'), ('blocked', 'Blocked'), ('deleted', 'Deleted')], db_index=True, default='active', max_length=10)),
                ('width', models.PositiveIntegerField(default=0)),
                ('height', models.PositiveIntegerField(default=0)),
                ('language', models.CharField(blank=True, max_length=10)),
                ('added', models.DateTimeField(auto_now_add=True)),
                ('film', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='backdrops', to='game.film')),
            ],
            options={
                'verbose_name': 'Kadr (backdrop)',
                'verbose_name_plural': 'Kadry (backdrops)',
                'ordering': ['-width'],
                'unique_together': {('film', 'file_path')},
            },
        ),
        migrations.CreateModel(
            name='Award',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('prize', models.CharField(choices=[('oscars', 'Academy Awards (Oscars)'), ('golden_globes', 'Golden Globes'), ('cannes', 'Cannes Film Festival'), ('bafta', 'BAFTA'), ('efa', 'European Film Awards'), ('venice', 'Venice Film Festival'), ('berlinale', 'Berlin International Film Festival (Berlinale)'), ('sundance', 'Sundance Film Festival')], max_length=20)),
                ('category', models.CharField(help_text='e.g. "Best Picture", "Palme d\'Or", "Best Director"', max_length=200)),
                ('year', models.IntegerField(help_text='Year the award was given')),
                ('person', models.CharField(blank=True, help_text='Who received it (actor/director name)', max_length=200)),
                ('film', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='awards', to='game.film')),
            ],
            options={
                'verbose_name': 'Award',
                'verbose_name_plural': 'Awards',
                'ordering': ['-year', 'prize'],
                'indexes': [models.Index(fields=['prize', 'year'], name='game_award_prize_617296_idx')],
            },
        ),
        migrations.CreateModel(
            name='GameRound',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('film_id', models.IntegerField(db_index=True, help_text='TMDB film ID')),
                ('shown_at', models.DateTimeField(auto_now_add=True)),
                ('guessed', models.BooleanField(default=False)),
                ('session', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='rounds', to='game.score')),
            ],
            options={
                'verbose_name': 'Game Round',
                'verbose_name_plural': 'Game Rounds',
                'ordering': ['-shown_at'],
                'indexes': [models.Index(fields=['film_id', 'guessed'], name='game_gamero_film_id_2aec3a_idx')],
            },
        ),
    ]
