# Generated by Django 5.2.15 on 2026-06-13 21:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0004_add_country_to_film'),
    ]

    operations = [
        migrations.AddField(
            model_name='score',
            name='duration_ms',
            field=models.IntegerField(blank=True, help_text='Session duration in milliseconds', null=True),
        ),
    ]
