# Generated by Django 5.2.15 on 2026-06-14 16:01

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0006_playerprofile'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='HeartedFrame',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('backdrop_path', models.CharField(help_text='TMDB backdrop file_path', max_length=120)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('film', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='hearts', to='game.film')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='hearted_frames', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Ulubiony kadr',
                'verbose_name_plural': 'Ulubione kadry',
                'ordering': ['-created'],
                'unique_together': {('user', 'film', 'backdrop_path')},
            },
        ),
    ]
